server:
  port: 8084

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 4
    instances:
      ratingService:
        baseConfig: default
      productService:
        baseConfig: default
      priceService:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
    instances:
      ratingService:
        baseConfig: default
      productService:
        baseConfig: default
      priceService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

application:
    name: INTEGRATION-SERVICE
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
